from util.jdk_data_export import export_package_detail_description_from_jdk
from util.json_util import write_json_to_file

description_json = export_package_detail_description_from_jdk()

write_json_to_file("jdk_package_detail_description.json", description_json)
